# Neural Network from Scratch

The simplest equation of a sample layer:
***y = w1x1 + w2x2 + w3x3 + ... + wnxxn + b***;
<br><br>
b = bias

#### Basic neuron with 3 inputs

In [2]:
# Assuming Values

inputs = [1.2, 5.1, 2.1]  # Input Layer with 3 units or Neuron
weights = [3.1, 2.1, 8.7] # Weights of Vectors
bias = 3.0                #Bias

# Implementing the equation in code

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

# By printing this we are getting to know that, what output this layer will generate
print(output)

35.7


#### a simple layer of neurons, with 4 inputs & 3 hidden layers

In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]  # Input Layer with 4 units or Neurons

weights1 = [ 0.2, 0.8, -0.5, 1.0]

weights2 = [0.5, -0.91, 0.26, -0.5]

weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]

print(output)

[4.8, 1.21, 2.385]


#### Doing dot product with a layer of neurons and multiple inputs

In [4]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


#### Layers and Objects

In [10]:
np.random.seed(0)

x = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.rand(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(x)
print('Layer 01\n', layer1.output)

layer2.forward(layer1.output)
print("\nLayer 02\n", layer2.output)

Layer 01
 [[ 0.44336001  0.32275945  0.61719927  0.71943905  0.35786764]
 [ 0.37096311  0.31298567  0.67615869  0.6538797   0.44335054]
 [ 0.3463683   0.18378799  0.27120932  0.42165082 -0.00617808]]

Layer 02
 [[0.09457125 0.18292227]
 [0.09125376 0.17749814]
 [0.05130749 0.09895662]]
