# Arrays

In [2]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr = numpy.array(arr, float)[::-1]
    return arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 5 6 -88 6 -9
[ -9.   6. -88.   6.   5.   2.   1.]


# Shape and Reshape

In [3]:
import numpy

arr = input().strip().split(' ')
arr = numpy.array(arr, int)

print(numpy.reshape(arr, (3,3)))

1 2 3 5 4 8 6 9 8
[[1 2 3]
 [5 4 8]
 [6 9 8]]


# Zeros and Ones

In [4]:
import numpy as np

arr = list(map(int, input().split()))

print(np.zeros((arr), dtype = 'int'))
print(np.ones((arr), dtype = 'int'))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [5]:
import numpy
numpy.set_printoptions(legacy='1.13')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
